# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='sluf',
            new_name='slug',
        ),
    ]
