# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20161114_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='strain_type',
            field=models.CharField(choices=[('indica', 'Indica'), ('sativa', 'Sativa'), ('hybrid', 'Hybrid')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
