# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_strain_strain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='initials',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
