# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_strain_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='initials',
            field=models.CharField(max_length=3),
        ),
    ]
