# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20161117_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='description',
            field=models.TextField(),
        ),
    ]
