# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20161118_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='strength',
        ),
        migrations.AddField(
            model_name='strain',
            name='attributes',
            field=models.CharField(choices=[('effects', (('sleepy', 'Sleepy'), ('creative', 'Creative'), ('hungry', 'Hungry'), ('giggles', 'Giggles'), ('relaxed', 'Relaxed'), ('happy', 'Happy'))), ('medical', (('pain', 'Pain'), ('stress', 'Stress'), ('insomnia', 'Insomnia'), ('depression', 'Depression'), ('lack-of-appetite', 'Lack of Appetite'))), ('drawbacks', (('paranoia', 'Paranoia'), ('cotton-mouth', 'Cotton Mouth'), ('dry-eyes', 'Dry Eyes'), ('headache', 'Headache')))], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
