# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20161121_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='drawbacks',
            field=models.CharField(choices=[('paranoia', 'Paranoia'), ('cotton-mouth', 'Cotton Mouth'), ('dry-eyes', 'Dry Eyes'), ('headache', 'Headache')], max_length=15),
        ),
        migrations.AlterField(
            model_name='strain',
            name='effects',
            field=models.CharField(choices=[('sleepy', 'Sleepy'), ('creative', 'Creative'), ('hungry', 'Hungry'), ('giggles', 'Giggles'), ('relaxed', 'Relaxed'), ('happy', 'Happy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='strain',
            name='medical',
            field=models.CharField(choices=[('pain', 'Pain'), ('stress', 'Stress'), ('insomnia', 'Insomnia'), ('depression', 'Depression'), ('lack-of-appetite', 'Lack of Appetite')], max_length=20),
        ),
    ]
