# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20161121_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='drawbacks',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='medical',
        ),
        migrations.AddField(
            model_name='strain',
            name='cotton_mouth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='creative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='depression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='dry_eyes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='giggles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='headache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='hungry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='insomnia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='lack_of_appetite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='pain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='paranoia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='relaxed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='sleepy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strain',
            name='stress',
            field=models.IntegerField(default=0),
        ),
    ]
