# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20161122_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='eight_price',
        ),
        migrations.AddField(
            model_name='strain',
            name='eighth_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strain',
            name='half_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strain',
            name='ounce_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strain',
            name='quarter_price',
            field=models.IntegerField(default=0),
        ),
    ]
